files_to_sync:
  - src: .distro/
    dest: ./
    delete: true
    filters:
      - "protect .git*"
      - "protect sources"
      - "protect changelog"
      - "protect gating.yaml"
      # Temporary workaround until
      # https://github.com/packit/packit/pull/2573
      - "- json-schema-validator.spec"
  - .packit.yaml

upstream_package_name: json-schema-validator
specfile_path: .distro/json-schema-validator.spec
downstream_package_name: json-schema-validator
update_release: false

targets: &targets
  - fedora-all-x86_64
  # TODO: aarch64 is failing at test
  # JSON-Suite::Optional::Format::idn-email
  # - fedora-all-aarch64

_:
  # Job templates
  - &build-in-packit
    job: copr_build
  - &build-in-lecris
    <<: *build-in-packit
    owner: "@scikit-build"
  - &tests
    job: tests
    fmf_path: .distro
    identifier: downstream

jobs:
  # Upstream jobs
  - <<: *build-in-lecris
    trigger: release
    project: release
#  - <<: *tests
#    trigger: release
  - <<: *build-in-lecris
    trigger: commit
    branch: main
    project: nightly
#  - <<: *tests
#    trigger: commit
#    branch: main
  - <<: *build-in-packit
    trigger: pull_request
#  - <<: *tests
#    trigger: pull_request
  # Downstream jobs
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
